# primary
background = #00101e
foreground = #ffffff
cursor-color = #00e3ff
cursor-text = #0e091d

# normal colors
palette = 0=#000000
#000000
palette = 1=#a80006
#a80006
palette = 2=#06bb00
#06bb00
palette = 3=#ffa412
#ffa412
palette = 4=#30c0ff
#30c0ff
palette = 5=#cc44be
#cc44be
palette = 6=#20d2ff
#20d2ff
palette = 7=#620090
#620090

# bright colors
palette = 8=#505050
#505050
palette = 9=#ff0000
#ff0000
palette = 10=#1eff00
#1eff00
palette = 11=#efcb29
#efcb29
palette = 12=#30d0ff
#30d0ff
palette = 13=#f540fb
#f540fb
palette = 14=#30d0ff
#30d0ff
palette = 15=#ffffff
#ffffff

# # normal colors
# palette = 0=#004075
# #004075
# palette = 1=#14ab00
# #14ab00
# palette = 2=#af3ed1
# #af3ed1
# palette = 3=#ffa412
# #ffa412
# palette = 4=#30d0ff
# #30d0ff
# palette = 5=#ff0000
# #cc44be
# palette = 6=#20aaff
# #20aaff
# palette = 7=#620090
# #620090

# # bright colors
# palette = 8=#ff0000
# #1163a6
# palette = 9=#faaaa9
# #faaaa9
# palette = 10=#ff0000
# #ff0000
# palette = 11=#efcb29
# #efcb29
# palette = 12=#40d0f0
# #40d0f0
# palette = 13=#ead7e7
# #ead7e7
# palette = 14=#ffad14
# #ffad14
# palette = 15=#f540fb
# #f540fb
